---
title: bibletld on github
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
#theme: bulma-clean-theme
remote_theme: chrisrhymes/bulma-clean-theme
